package com.juzhai.future.passport.mapper;

import com.juzhai.future.passport.model.Passport;
import com.juzhai.future.passport.model.PassportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PassportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_passport
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int countByExample(PassportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_passport
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int deleteByExample(PassportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_passport
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_passport
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int insert(Passport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_passport
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int insertSelective(Passport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_passport
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    List<Passport> selectByExample(PassportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_passport
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    Passport selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_passport
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int updateByExampleSelective(@Param("record") Passport record, @Param("example") PassportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_passport
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int updateByExample(@Param("record") Passport record, @Param("example") PassportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_passport
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int updateByPrimaryKeySelective(Passport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_passport
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int updateByPrimaryKey(Passport record);
}