package com.juzhai.future.passport.mapper;

import com.juzhai.future.passport.model.Thirdparty;
import com.juzhai.future.passport.model.ThirdpartyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThirdpartyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_thirdparty
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int countByExample(ThirdpartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_thirdparty
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int deleteByExample(ThirdpartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_thirdparty
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_thirdparty
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int insert(Thirdparty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_thirdparty
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int insertSelective(Thirdparty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_thirdparty
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    List<Thirdparty> selectByExample(ThirdpartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_thirdparty
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    Thirdparty selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_thirdparty
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int updateByExampleSelective(@Param("record") Thirdparty record, @Param("example") ThirdpartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_thirdparty
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int updateByExample(@Param("record") Thirdparty record, @Param("example") ThirdpartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_thirdparty
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int updateByPrimaryKeySelective(Thirdparty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_thirdparty
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int updateByPrimaryKey(Thirdparty record);
}