package com.juzhai.future.passport.mapper;

import com.juzhai.future.passport.model.TpUser;
import com.juzhai.future.passport.model.TpUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TpUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int countByExample(TpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int deleteByExample(TpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int insert(TpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int insertSelective(TpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    List<TpUser> selectByExample(TpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    TpUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int updateByExampleSelective(@Param("record") TpUser record, @Param("example") TpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int updateByExample(@Param("record") TpUser record, @Param("example") TpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int updateByPrimaryKeySelective(TpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tp_user
     *
     * @mbggenerated Fri Mar 22 11:01:10 CST 2013
     */
    int updateByPrimaryKey(TpUser record);
}